import { deriveGenome, snapshotSpellSettings, validateSpellSettings } from './spell-contract.js';

export const HOUSE_PALETTE = Object.freeze({
  fire: ['#ff6a3c', '#ffbf58', '#5b170f'],
  water: ['#3fb8c9', '#c8f3fb', '#164b70'],
  earth: ['#a08a63', '#d5b78c', '#35291e'],
  air: ['#bfe8df', '#f3fffd', '#41666a'],
});

// This is the source of truth used by both the Atlas bootstrap and the
// intentional offline shelf. These pages are visual snapshots, not twelve
// aliases of the renderer defaults.
export const HOUSE_SEED_SPELLS = Object.freeze([
  { slug: 'cinderwake', name: 'Cinderwake', element: 'fire', incantation: 'a low, hungry flame that hugs the ground and detonates twice', lore: 'It runs close to the floor, red at its teeth and gold at its heart, following every curve with a starving patience. The first strike leaves a seam of warming ash; the second arrives just as the embers settle, opening the darkness like a held door.', tags: ['hungry', 'low', 'double-strike'], settingsPatch: { 'global.speed': 1.18, 'global.particleSize': 0.68, 'global.turbulence': 2.8, 'global.glow': 1.8, 'fire.speed': 12.4, 'fire.lifetime': 2, 'fire.flameWidth': 0.28, 'fire.flameHeight': 1.5, 'fire.flameTurbulence': 4.4, 'fire.glow': 3.6, 'fire.streamLength': 11.5, 'fire.emberRate': 285, 'fire.explosionSize': 4.8 } },
  { slug: 'sun-petal', name: 'Sun-Petal', element: 'fire', incantation: 'a slow blossom of white-gold fire that opens at the end of the path', lore: 'A patient spark travels slowly enough to gather the color of everything it passes. At the end of the path it opens into white-gold petals, neither violent nor shy, and holds its warm light for a breath before folding quietly back into the air.', tags: ['white-gold', 'slow', 'blossom'], settingsPatch: { 'global.speed': 0.58, 'global.particleSize': 1.55, 'global.turbulence': 0.8, 'global.glow': 3.65, 'fire.speed': 5.8, 'fire.lifetime': 5.4, 'fire.flameWidth': 0.8, 'fire.flameHeight': 3.8, 'fire.flameTurbulence': 1.1, 'fire.glow': 7.2, 'fire.streamLength': 14, 'fire.emberRate': 80, 'fire.explosionSize': 8.4 } },
  { slug: 'vermilion-adder', name: 'Vermilion Adder', element: 'fire', incantation: 'a fast violet-red serpent that strikes hard at the finish', lore: 'Violet fire threads a red body that refuses straight roads, coiling around each turn like a watchful serpent. At the finish it narrows, gathers heat beneath a dark edge, and snaps forward with a bright hard bite that leaves a fleeting ember scar above the ground.', tags: ['violet-red', 'serpent', 'striking'], settingsPatch: { 'global.speed': 2.15, 'global.particleSize': 0.34, 'global.turbulence': 3.7, 'global.glow': 4.1, 'fire.speed': 25.6, 'fire.lifetime': 1.35, 'fire.flameWidth': 0.14, 'fire.flameHeight': 2.2, 'fire.flameTurbulence': 5.5, 'fire.glow': 5.1, 'fire.streamLength': 7.4, 'fire.emberRate': 350, 'fire.explosionSize': 9.4 } },
  { slug: 'moon-whip', name: 'Moon Whip', element: 'water', incantation: 'a thin cold arc of moonlit water that snaps at the end', lore: 'Drawn from a low tide beneath a cloudless moon, this narrow lash travels cold and almost silent. It curves with the caster’s hand, then delivers one clean crack at the far end, scattering pale foam that glints briefly before the water remembers its calm.', tags: ['cold', 'precise', 'lunar'], settingsPatch: { 'global.speed': 1.45, 'global.particleSize': 0.38, 'global.turbulence': 1.2, 'global.glow': 0.9, 'water.speed': 21.5, 'water.lifetime': 1.8, 'water.radius': 0.12, 'water.crest': 1.15, 'water.waveAmplitude': 0.1, 'water.chop': 0.25, 'water.flowSpeed': 3.8, 'water.foam': 0.6, 'water.glow': 1.4, 'water.splashSize': 2.6, 'water.splashIntensity': 0.75 } },
  { slug: 'harbor-bell', name: 'Harbor Bell', element: 'water', incantation: 'a heavy, slow swell that rings out wide foam rings on impact', lore: 'A broad blue weight rolls forward without hurry, carrying the stillness of a harbor at dusk. On impact, it becomes a round, ringing swell: foam circles travel outward in measured layers, as though the sea has answered an old bell sounded beneath the quay.', tags: ['heavy', 'slow', 'foam'], settingsPatch: { 'global.speed': 0.52, 'global.particleSize': 2.2, 'global.turbulence': 0.45, 'global.glow': 2.8, 'water.speed': 4.2, 'water.lifetime': 5.6, 'water.radius': 1.25, 'water.crest': 2.8, 'water.waveAmplitude': 0.85, 'water.chop': 1.45, 'water.flowSpeed': 0.7, 'water.foam': 4.4, 'water.glow': 4.9, 'water.splashSize': 9.3, 'water.splashIntensity': 3.8 } },
  { slug: 'undertow', name: 'Undertow', element: 'water', incantation: 'a deep teal surge that drags low and crowns tall', lore: 'Deep teal water keeps low along the path, drawing loose light and drifting mist toward its patient center. Near the finish it rises into a tall crowned surge, not angry but insistent, leaving a cool pull in the air after the visible water has gone.', tags: ['teal', 'low', 'crowned'], settingsPatch: { 'global.speed': 1.06, 'global.particleSize': 1.05, 'global.turbulence': 2.55, 'global.glow': 1.45, 'water.speed': 10.5, 'water.lifetime': 4.2, 'water.radius': 0.72, 'water.crest': 3.3, 'water.waveAmplitude': 0.72, 'water.chop': 2.65, 'water.flowSpeed': 2.3, 'water.foam': 2.8, 'water.glow': 2.3, 'water.splashSize': 6.2, 'water.splashIntensity': 1.8 } },
  { slug: 'terrace-of-the-patient-king', name: 'Terrace of the Patient King', element: 'earth', incantation: 'a slow, wide paving that ends in a tall tower', lore: 'Stone rises in deliberate syllables, each wide plate carrying the weight and memory of the one beneath it. The path becomes a patient road before ending in a tall, quiet tower, a place from which even hurried thoughts seem willing to look farther.', tags: ['steady', 'wide', 'regal'], settingsPatch: { 'global.speed': 0.62, 'global.particleSize': 1.65, 'global.turbulence': 0.5, 'global.glow': 0.85, 'earth.speed': 4.5, 'earth.lifetime': 6, 'earth.crustWidth': 7.8, 'earth.plateSize': 2.4, 'earth.rockSize': 1.2, 'earth.rockRandomness': 0.2, 'earth.riseHeight': 3.2, 'earth.glow': 1.1, 'earth.towerHeight': 15.2, 'earth.towerWidth': 2.5 } },
  { slug: 'gravel-psalm', name: 'Gravel Psalm', element: 'earth', incantation: 'quick shallow plates that crack early and settle softly', lore: 'Small plates answer in a quick rhythm, breaking open before their edges fully meet the ground. Dust lifts, cracks speak, and the fragments settle with unexpected softness, as if the earth has completed a familiar prayer and no longer needs to raise its voice.', tags: ['quick', 'shallow', 'soft'], settingsPatch: { 'global.speed': 1.48, 'global.particleSize': 0.4, 'global.turbulence': 3, 'global.glow': 0.42, 'earth.speed': 18.5, 'earth.lifetime': 1.6, 'earth.crustWidth': 1.35, 'earth.plateSize': 0.35, 'earth.rockSize': 0.22, 'earth.rockRandomness': 1.75, 'earth.riseHeight': 0.75, 'earth.glow': 0.65, 'earth.towerHeight': 3.2, 'earth.towerWidth': 0.5 } },
  { slug: 'basalt-procession', name: 'Basalt Procession', element: 'earth', incantation: 'narrow dark plates marching in file to a squat obelisk', lore: 'Dark slabs move in single file with no wasted motion, narrowing the world into a procession of weight and purpose. Their final obelisk rises short, broad, and certain, marking a road that exists only while the incantation is still warm in the caster’s mouth.', tags: ['basalt', 'narrow', 'obelisk'], settingsPatch: { 'global.speed': 0.98, 'global.particleSize': 2.4, 'global.turbulence': 1.7, 'global.glow': 1.3, 'earth.speed': 8.6, 'earth.lifetime': 3.8, 'earth.crustWidth': 2.5, 'earth.plateSize': 0.7, 'earth.rockSize': 1.5, 'earth.rockRandomness': 0.9, 'earth.riseHeight': 1.4, 'earth.glow': 2.4, 'earth.towerHeight': 5.4, 'earth.towerWidth': 3.4 } },
  { slug: 'sparrow-gale', name: 'Sparrow Gale', element: 'air', incantation: 'a quick, light spiral that scatters leaves and is gone', lore: 'A small wind begins with a bird’s sudden nerve, lifting leaves, dust, and stray threads of light before anyone has time to brace. It spirals once, laughs through the open space, and vanishes so quickly that only the leaves remember its direction.', tags: ['quick', 'light', 'restless'], settingsPatch: { 'global.speed': 1.72, 'global.particleSize': 0.28, 'global.turbulence': 2.4, 'global.glow': 0.5, 'air.speed': 24.5, 'air.lifetime': 1.3, 'air.ribbonWidth': 0.25, 'air.ribbonLength': 6.8, 'air.spiralRadius': 0.45, 'air.vortexStrength': 0.9, 'air.turbulence': 2.6, 'air.glow': 0.8, 'air.tornadoHeight': 4 } },
  { slug: 'whistling-door', name: 'Whistling Door', element: 'air', incantation: 'a slow wide vortex that ends in a pressure clap', lore: 'The air opens gradually into a wide pale doorway, turning on an invisible hinge with a low, clear whistle. At the end it closes in a pressure clap that rearranges dust, sleeves, and attention alike, leaving the room briefly aware of its own stillness.', tags: ['wide', 'vortex', 'pressure'], settingsPatch: { 'global.speed': 0.64, 'global.particleSize': 2.6, 'global.turbulence': 0.55, 'global.glow': 2.2, 'air.speed': 5.6, 'air.lifetime': 5.4, 'air.ribbonWidth': 3.6, 'air.ribbonLength': 18.5, 'air.spiralRadius': 2.8, 'air.vortexStrength': 4.3, 'air.turbulence': 0.4, 'air.glow': 3.8, 'air.tornadoHeight': 16 } },
  { slug: 'sky-lathe', name: 'Sky Lathe', element: 'air', incantation: 'a tight, fast helix that polishes the air white', lore: 'A tight helix climbs so fast that the center burns white, polishing the air into a narrow luminous column. It does not tear the sky; it burnishes it, lifting loose brightness along its spiral and leaving the stage cleaner, sharper, and briefly more awake.', tags: ['tight', 'fast', 'white'], settingsPatch: { 'global.speed': 2.25, 'global.particleSize': 0.7, 'global.turbulence': 3.65, 'global.glow': 4.35, 'air.speed': 31.5, 'air.lifetime': 2, 'air.ribbonWidth': 0.12, 'air.ribbonLength': 14.5, 'air.spiralRadius': 0.24, 'air.vortexStrength': 3.2, 'air.turbulence': 2.9, 'air.glow': 4.8, 'air.tornadoHeight': 12.8 } },
]);

export function houseSpellSettings(settingsPatch) {
  const settings = snapshotSpellSettings();
  for (const [path, value] of Object.entries(settingsPatch)) {
    const [section, key] = path.split('.');
    if (!section || !key || !Object.hasOwn(settings, section) || !Object.hasOwn(settings[section], key)) {
      throw new Error(`Unknown House spell setting: ${path}`);
    }
    settings[section][key] = value;
  }
  const checked = validateSpellSettings(settings);
  if (!checked.ok) throw new Error(`Invalid House spell settings: ${checked.issues.join('; ')}`);
  return checked.value;
}

export function houseSpellForClient(seed) {
  const settings = houseSpellSettings(seed.settingsPatch);
  return {
    ...seed,
    settings,
    genome: deriveGenome(settings, seed.element),
    portrait: { imageUrl: null, palette: HOUSE_PALETTE[seed.element] },
    stats: { casts: 0, remixes: 0 },
    lineage: { parentId: null, rootId: seed.slug, depth: 0 },
    creator: { handle: 'The First Binder' },
  };
}
