// Exact numerical bounds from the persisted controls in src/ui/Editor.js.
// `Editor.range()` reads this manifest at runtime and spell validation reads it
// at bind/load time, so a snapshot cannot be legal in one surface and altered
// in the other.
const define = (range, ...paths) => paths.map((path) => [
  path,
  Object.freeze({ min: range[0], max: range[1], step: range[2] }),
]);

export const EXACT_SPELL_RANGES = Object.freeze(Object.fromEntries([
  ...define([0.05, 2, 0.01], 'global.timeScale'),
  ...define([0.1, 4, 0.01], 'global.speed', 'global.lifetime', 'global.noiseFrequency', 'global.lightRadius', 'water.rippleSpeed', 'earth.riseHeight', 'earth.towerRiseTime', 'earth.shakeDuration'),
  ...define([0, 5, 0.01], 'global.glow', 'fire.flightArc', 'fire.flameCurl', 'fire.lick', 'fire.smokeSpeed', 'fire.fresnel', 'water.fresnel', 'water.foam', 'water.splashIntensity', 'air.vortexStrength', 'air.glow', 'air.fresnel', 'air.burstIntensity'),
  ...define([0, 2, 0.01], 'global.shaderIntensity', 'global.opacity', 'global.randomness', 'trail.opacity', 'trail.noiseStrength', 'fire.flameWarp', 'fire.wisps', 'fire.flicker', 'fire.opacity', 'fire.smokeDensity', 'fire.explosionFlash', 'water.surge', 'water.detail', 'water.crestSharpness', 'water.opacity', 'water.mistDensity', 'water.explosionFlash', 'earth.rockRandomness', 'earth.crackWidth', 'earth.groundDisplacement', 'earth.explosionFlash', 'air.ribbonOpacity', 'air.haze', 'air.opacity', 'air.explosionFlash', 'post.bloomThreshold', 'post.flashStrength'),
  ...define([0, 3, 0.01], 'global.noiseStrength', 'global.distortion', 'global.fresnel', 'global.particleCount', 'global.emissionRate', 'global.explosionIntensity', 'global.cameraShake', 'global.animationSpeed', 'trail.sparkle', 'fire.wakeSpread', 'fire.wakeRise', 'fire.vortex', 'fire.ringFrequency', 'fire.shred', 'fire.noiseStrength', 'fire.emberCount', 'fire.explosionShake', 'water.wakeSag', 'water.chop', 'water.skyReflection', 'water.explosionShake', 'earth.crackDepth', 'earth.dustAmount', 'air.turbulence', 'air.noiseStrength', 'air.dustAmount', 'air.explosionShake', 'post.bloomStrength', 'post.chromaticAberration'),
  ...define([0, 4, 0.01], 'global.noiseSpeed', 'global.turbulence', 'global.lightIntensity', 'fire.noiseSpeed', 'fire.scatter', 'fire.volumeDensity', 'fire.heatDistortion', 'water.height', 'water.swirl', 'water.depthDensity', 'water.refraction', 'water.envIntensity', 'water.translucency', 'earth.sinkDelay', 'earth.tumble', 'earth.glow', 'earth.shakeIntensity', 'air.distortion'),
  ...define([0.1, 3, 0.01], 'global.particleLifetime', 'global.particleSpeed', 'global.particleSize', 'earth.rockCount', 'earth.rockSize', 'post.exposure'),
  ...define([0.05, 3, 0.01], 'trail.width', 'fire.flameWidth', 'water.radius', 'water.foamSize', 'air.dustSize'),
  ...define([0.05, 1, 0.01], 'trail.length', 'fire.softness'),
  ...define([0, 10, 0.01], 'trail.glow', 'fire.glow', 'water.surgeSpeed'),
  ...define([0, 6, 0.01], 'trail.flowSpeed', 'fire.ringSpeed', 'fire.flameTurbulence', 'fire.buoyancy', 'fire.soot', 'water.surgeLength', 'water.flowSpeed', 'water.specular', 'water.glow'),
  ...define([0.1, 8, 0.01], 'trail.noiseFrequency', 'water.waveFrequency'),
  ...define([0.1, 6, 0.01], 'trail.dissolveSpeed', 'fire.noiseFrequency', 'water.noiseFrequency', 'air.noiseFrequency'),
  ...define([0, 1, 0.01], 'trail.taper', 'fire.heatFollow', 'fire.paletteBlend', 'air.filamentSharpness'),
  ...define([0.02, 1, 0.01], 'trail.softness', 'fire.coreClarity', 'earth.plateThickness'),
  ...define([0.01, 1, 0.01], 'trail.height'),
  ...define([0.5, 40, 0.1], 'fire.speed', 'water.speed', 'earth.speed', 'air.speed', 'fire.lightRadius', 'water.lightRadius', 'earth.lightRadius', 'air.lightRadius'),
  ...define([0.2, 10, 0.1], 'fire.lifetime', 'water.lifetime', 'earth.lifetime', 'air.lifetime'),
  ...define([0, 8, 0.01], 'fire.flightHeight', 'fire.flameSpeed', 'air.swirlSpeed'),
  ...define([1, 5, 0.01], 'fire.headSize', 'water.headSize'),
  ...define([1, 6, 0.01], 'fire.flameHeight'),
  ...define([0.5, 20, 0.1], 'fire.streamLength', 'water.rippleSize'),
  ...define([0, 0.8, 0.01], 'fire.bulge'),
  ...define([0.1, 2, 0.01], 'fire.bulgeScale'),
  ...define([0, 1.5, 0.01], 'fire.detachment', 'fire.tailHeat', 'water.waveAmplitude', 'water.transparency', 'water.shred', 'earth.plateLift', 'earth.plateSpread', 'air.tornadoLean', 'post.bloomRadius', 'post.vignette'),
  ...define([0.15, 2, 0.01], 'fire.tongueStretch', 'fire.streamStretch'),
  ...define([2, 5, 1], 'fire.detailOctaves'),
  ...define([1500, 6000, 10], 'fire.tempCore'),
  ...define([800, 3000, 10], 'fire.tempEdge'),
  ...define([1, 8, 0.05], 'fire.emissionCurve'),
  ...define([0.4, 4, 0.01], 'fire.heatFocus'),
  ...define([0.2, 4, 0.01], 'fire.heatFalloff', 'earth.rockSpacing'),
  ...define([0.2, 8, 0.05], 'fire.scatterFalloff', 'fire.smokeLifetime', 'earth.towerRockRadius', 'air.tornadoRadius'),
  ...define([6, 72, 1], 'fire.volumeSteps'),
  ...define([0, 400, 1], 'fire.emberRate', 'air.dustRate'),
  ...define([0.01, 0.6, 0.005], 'fire.emberSize', 'earth.debrisSize'),
  ...define([0, 10, 0.05], 'fire.emberSpeed', 'water.dropletSpeed'),
  ...define([0.1, 5, 0.05], 'fire.emberLifetime', 'water.dropletLifetime', 'earth.debrisLifetime'),
  ...define([0, 200, 1], 'fire.sparkRate', 'water.foamRate', 'earth.pebbleRate', 'air.leafCount'),
  ...define([0, 20, 0.1], 'fire.sparkSpeed', 'water.spraySpeed', 'water.foamSpread', 'earth.debrisVelocity'),
  ...define([0.1, 5, 0.01], 'fire.smokeSize', 'water.mistSize', 'earth.dustSize', 'earth.towerWidth'),
  ...define([0.2, 6, 0.05], 'fire.distortionRadius', 'water.mistLifetime', 'earth.dustLifetime', 'air.leafLifetime', 'air.tornadoDuration'),
  ...define([0.2, 10, 0.05], 'fire.explosionSize', 'water.streamStretch'),
  ...define([0, 8, 0.05], 'fire.explosionBrightness', 'earth.towerHold'),
  ...define([1, 4, 0.01], 'water.crest'),
  ...define([0.5, 24, 0.1], 'water.streamLength'),
  ...define([8, 64, 1], 'water.volumeSteps'),
  ...define([0.2, 6, 0.01], 'water.foamSharpness'),
  ...define([0.02, 2, 0.01], 'water.shredDepth'),
  ...define([0, 800, 1], 'water.dropletRate'),
  ...define([0.005, 0.5, 0.005], 'water.dropletSize'),
  ...define([0, 600, 1], 'water.sprayRate'),
  ...define([0.1, 6, 0.05], 'water.foamLifetime'),
  ...define([0, 30, 0.5], 'water.wakeRate'),
  ...define([0.2, 12, 0.05], 'water.splashSize'),
  ...define([0, 40, 1], 'water.crownJets'),
  ...define([0.5, 12, 0.1], 'water.foamLingering'),
  ...define([0.5, 10, 0.05], 'earth.crustWidth'),
  ...define([0.2, 3, 0.01], 'earth.crustDensity', 'earth.plateSize'),
  ...define([0.03, 1.5, 0.01], 'earth.paintTime'),
  ...define([0.02, 3, 0.01], 'earth.crackDelay'),
  ...define([0.05, 1.5, 0.01], 'earth.crackSharpness'),
  ...define([0, 1.6, 0.01], 'earth.plateTilt'),
  ...define([0.5, 14, 0.05], 'earth.riseSpeed'),
  ...define([0, 300, 1], 'earth.debrisRate'),
  ...define([0.5, 20, 0.05], 'earth.towerHeight'),
  ...define([0, 60, 1], 'earth.towerRocks'),
  ...define([1, 8, 1], 'air.ribbonCount'),
  ...define([0.05, 6, 0.01], 'air.ribbonWidth'),
  ...define([1, 24, 0.1], 'air.ribbonLength'),
  ...define([0.05, 4, 0.01], 'air.spiralRadius'),
  ...define([0, 3.14, 0.01], 'air.sheetTwist'),
  ...define([0, 20, 0.05], 'air.rotationSpeed'),
  ...define([1, 64, 1], 'air.filamentCount'),
  ...define([0.02, 0.8, 0.005], 'air.leafSize'),
  ...define([0, 12, 0.05], 'air.leafSpin'),
  ...define([1, 20, 0.1], 'air.tornadoHeight'),
  ...define([0.04, 0.8, 0.01], 'air.tornadoNeck'),
  ...define([1, 4, 1], 'air.tornadoShells'),
  ...define([0, 0.5, 0.01], 'air.tornadoRoughness'),
  ...define([0, 80, 0.1], 'fire.lightIntensity', 'water.lightIntensity', 'earth.lightIntensity', 'air.lightIntensity'),
  ...define([0.5, 2, 0.01], 'post.contrast', 'post.gain'),
  ...define([0, 2.5, 0.01], 'post.saturation'),
  ...define([-0.5, 0.5, 0.01], 'post.temperature'),
  ...define([-0.2, 0.2, 0.005], 'post.lift'),
  ...define([0, 0.2, 0.001], 'post.grain'),
]));
